name: Atualizar Base de Dados Diária

on:
  schedule:
    - cron: '0 9 * * *' # Roda todo dia às 09:00 UTC (06:00 Brasília)
  workflow_dispatch: # Permite rodar manualmente apertando um botão

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: |
          pip install pandas numpy requests

      - name: Executar script de atualização
        run: python atualizar_dados.py

      - name: Salvar alterações no GitHub
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add dados_25_26.csv
          git commit -m "Atualização automática dos dados: $(date +'%d/%m/%Y')" || exit 0
          git push
